# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3'
services:
  frontend:
    image: frontend
    container_name: frontend_container
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    depends_on:
      - api
  api:
    #    user: ${UID}:${GID}
    image: flask_api
    container_name: ml_api
    build:
      #      args:
      #        - UID=${UID}
      #        - GID=${GID}
      context: ./api
      target: build
    ports:
      - '5001:5001'
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
